version: '3'

services:
  web:
    image: php:7.4-apache
    container_name: mi-sitio-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - my-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mi-base-de-datos
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: TuPasswordDeSA
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
